### ISSUE TITLE
package as module

### ISSUE THREAD

**Issue by happyleavesaoc** [dj0wns/AoE_Rec_Opening_Analysis#2]
It would be helpful if this project was packaged as python module. Basically, 1) adding a `setup.py`, 2) moving files into a package directory. Then it can be `pip install`ed as a dependency.

I can submit a PR for this but it would probably be a breaking change on your side as files would move.

**Comment by dj0wns** [comment]
I'll look into doing that this weekend

**Comment by dj0wns** [comment]
I just packed it as the aoe-opening-data module. Let me know if that is sufficient for you or if anything else would help
